### ISSUE TITLE
meet exception "No qualifying bean of type 'com.thoughtworks.xstream.XStream' available" when start application

### ISSUE THREAD

**Issue by john9yang** [AxonIQ/giftcard-demo#150]
### Basic information

* JDK version: 11
* Complete executable reproducer if available (e.g. GitHub Repo):

### Steps to reproduce

1. start the app in idea or execute java -jar

### Expected behaviour

the application should started

### Actual behaviour

Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'serializer' defined in class path resource [org/axonframework/springboot/autoconfig/AxonAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.axonframework.serialization.Serializer]: Factory method 'serializer' threw exception; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.thoughtworks.xstream.XStream' available
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1391) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791) ~[spring-beans-5.3.23.jar:5.3.23]
	... 78 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.axonframework.serialization.Serializer]: Factory method 'serializer' threw exception; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.thoughtworks.xstream.XStream' available
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653) ~[spring-beans-5.3.23.jar:5.3.23]
	... 92 common frames omitted
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.thoughtworks.xstream.XStream' available
	at org.axonframework.springboot.autoconfig.AxonAutoConfiguration.lambda$buildSerializer$5(AxonAutoConfiguration.java:203) ~[axon-spring-boot-autoconfigure-4.6.1.jar:4.6.1]
	at java.base/java.util.Optional.orElseThrow(Optional.java:408) ~[na:na]
	at org.axonframework.springboot.autoconfig.AxonAutoConfiguration.buildSerializer(AxonAutoConfiguration.java:203) ~[axon-spring-boot-autoconfigure-4.6.1.jar:4.6.1]
	at org.axonframework.springboot.autoconfig.AxonAutoConfiguration.serializer(AxonAutoConfiguration.java:139) ~[axon-spring-boot-autoconfigure-4.6.1.jar:4.6.1]
	at org.axonframework.springboot.autoconfig.AxonAutoConfiguration$$EnhancerBySpringCGLIB$$8e4e8f9c.CGLIB$serializer$0(<generated>) ~[axon-spring-boot-autoconfigure-4.6.1.jar:4.6.1]
	at org.axonframework.springboot.autoconfig.AxonAutoConfiguration$$EnhancerBySpringCGLIB$$8e4e8f9c$$FastClassBySpringCGLIB$$61b7777c.invoke(<generated>) ~[axon-spring-boot-autoconfigure-4.6.1.jar:4.6.1]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.3.23.jar:5.3.23]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[spring-context-5.3.23.jar:5.3.23]
	at org.axonframework.springboot.autoconfig.AxonAutoConfiguration$$EnhancerBySpringCGLIB$$8e4e8f9c.serializer(<generated>) ~[axon-spring-boot-autoconfigure-4.6.1.jar:4.6.1]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.3.23.jar:5.3.23]
	... 93 common frames omitted

**Comment by gklijs** [comment]
Fixed with https://github.com/AxonIQ/giftcard-demo/pull/175 which moved the serialisation to Jackson instead.
